pipeline:
  name: Numpy CI Pipeline
  identifier: Numpy_CI_Pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.gitconnector
        repoName: numpy
        build: <+input>
  stages:
    - stage:
        name: Build Stage
        identifier: Build_Stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            key: py-cache-{{ checksum "requirements/all_requirements.txt" }}
            paths:
              - .venv
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Sh
                    command: |-
                      python -m venv .venv
                      . .venv/bin/activate

                      python -m pip install --upgrade pip
                      pip install -r ./requirements/all_requirements.txt
                      pip install pytest
              - step:
                  type: Run
                  name: Run Tests
                  identifier: Run_Tests
                  spec:
                    shell: Sh
                    command: |-
                      . .venv/bin/activate

                      pytest tests.py --junit-xml=report.xml
                    reports:
                      type: JUnit
                      spec:
                        path:
                          - report.xml
